# Generated by Django 5.2.6 on 2026-09-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentline',
            name='tax_type_snapshot',
            field=models.CharField(blank=True, choices=[('standard', 'Standard rated'), ('zero', 'Zero rated'), ('exempt', 'Exempt'), ('out_of_scope', 'Out of scope')], default='out_of_scope', max_length=20),
        ),
    ]
