"""DEVELOPMENT-ONLY demo data. Refuses to run unless DEBUG=True.

Creates a demo client, a few catalog items, a quotation and an invoice so
developers can exercise the UI. Never run in production.
"""
from datetime import timedelta
from decimal import Decimal

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.utils import timezone

from billing.models import (
    CompanySettings, Client, Product, TaxCategory, Quotation, Invoice,
)
from billing import services
from billing.numbering import next_document_number


class Command(BaseCommand):
    help = 'Seed DEMO data (dev only; refuses to run when DEBUG=False).'

    def handle(self, *args, **options):
        if not settings.DEBUG:
            raise CommandError('seed_demo is development-only. It refuses to run with DEBUG=False.')

        company = CompanySettings.load()
        std_tax = TaxCategory.objects.filter(is_default=True).first()

        client, _ = Client.objects.get_or_create(
            name='Demo Business Ltd',
            defaults={
                'client_type': Client.BUSINESS,
                'contact_person': 'Jane Demo',
                'email': 'demo@example.com',
                'phone': '+254700000000',
                'billing_address': 'Demo House, Demo Road, Nairobi',
                'status': Client.ACTIVE,
            },
        )

        items = [
            ('Managed IT Support — Standard', 'service', Decimal('35000.00'), 'month'),
            ('24-Port Gigabit Switch', 'product', Decimal('18500.00'), 'item'),
            ('Network Installation (per point)', 'service', Decimal('3500.00'), 'point'),
            ('Cloud Backup — 1TB', 'service', Decimal('5000.00'), 'month'),
        ]
        products = []
        for name, ptype, price, unit in items:
            p, _ = Product.objects.get_or_create(
                name=name,
                defaults={
                    'product_type': ptype, 'selling_price': price, 'unit': unit,
                    'tax_category': std_tax, 'category': 'Demo',
                    'public_show': False,
                },
            )
            products.append(p)

        if not Quotation.objects.exists():
            q = Quotation.objects.create(
                client=client,
                issue_date=timezone.localdate(),
                valid_until=timezone.localdate() + timedelta(days=30),
                notes='Demo quotation generated by seed_demo.',
            )
            q.number = next_document_number('quotation')
            q.save(update_fields=['number'])
            services.create_quotation_lines(q, [
                {'description': p.name, 'unit': p.unit, 'quantity': Decimal('2'),
                 'unit_price': p.selling_price, 'tax_category': std_tax, 'catalog_item': p}
                for p in products[:2]
            ])
            q.mark_sent()
            self.stdout.write(f'Created demo quotation {q.number}')

        if not Invoice.objects.exists():
            inv = Invoice.objects.create(
                client=client,
                issue_date=timezone.localdate(),
                due_date=timezone.localdate() + timedelta(days=14),
                notes='Demo invoice generated by seed_demo.',
            )
            inv.number = next_document_number('invoice')
            inv.save(update_fields=['number'])
            services.create_quotation_lines(inv, [
                {'description': products[2].name, 'unit': products[2].unit,
                 'quantity': Decimal('10'), 'unit_price': products[2].selling_price,
                 'tax_category': std_tax, 'catalog_item': products[2]},
                {'description': products[3].name, 'unit': products[3].unit,
                 'quantity': Decimal('1'), 'unit_price': products[3].selling_price,
                 'tax_category': std_tax, 'catalog_item': products[3]},
            ])
            inv.status = Invoice.ISSUED
            inv.save(update_fields=['status'])
            self.stdout.write(f'Created demo invoice {inv.number}')

        self.stdout.write(self.style.SUCCESS('Demo data ready (development only).'))
